Repository EtherealEngine/ir-engine-docs, pull requests merged in 2024-07, with the labels that each got.

#1 Added the initial default project files in preparation for deployment
  README.md
  astro.config.mjs
  package-lock.json
  package.json
  public/favicon.svg
  src/assets/houston.webp
  src/content/config.ts
  src/content/docs/guides/example.md
  src/content/docs/index.mdx
  src/content/docs/reference/example.md
  src/env.d.ts
  tsconfig.json
Labels: enhancement

#2 IR engine Docs site IaC and Deploy; IR-3398
  .github/workflows/deploy-docs-site.yml
  .gitignore
  iac/modules/static-website/cloudfront.tf
  iac/modules/static-website/error.html
  iac/modules/static-website/index.html
  iac/modules/static-website/outputs.tf
  iac/modules/static-website/s3.tf
  iac/modules/static-website/url-redirect.js
  iac/modules/static-website/variables.tf
  iac/prd/account.hcl
  iac/prd/us-east-1/ir-engine-docs/terragrunt.hcl
  iac/prd/us-east-1/region.hcl
  iac/terragrunt.hcl
Labels: verified-contributor

#4 Directories and Markdown file placeholders
  get-started/creating-projects/create-a-project.md
  get-started/creating-projects/understanding-entities.md
  get-started/initial-setup/sign-up-and-login.md
  get-started/initial-setup/system-requirements.md
  get-started/ir-engine-studio/introduction-to-the-studio.md
  get-started/ir-engine-studio/navigation-controls.md
  get-started/ir-engine-studio/studio-interface/file-browser-panel.md
  get-started/ir-engine-studio/studio-interface/hamburger-menu.md
  get-started/ir-engine-studio/studio-interface/hierarchy-tab.md
  get-started/ir-engine-studio/studio-interface/materials-inspector.md
  get-started/ir-engine-studio/studio-interface/properties-panel.md
  get-started/ir-engine-studio/studio-interface/viewport-panel.md
  introduction/about-this-site.md
  introduction/ir-engine-overview.md
  introduction/key-terminology.md
  publishing/publish-your-projects.md
  scene-development/building-and-managing-scenes/add-scenes-to-your-project.md
  scene-development/building-and-managing-scenes/scene-budget-guidelines.md
  scene-development/entities-and-components.md
  scene-development/working-with-assets/asset-types.md
  scene-development/working-with-assets/import-assets-and-files.md
  scene-development/working-with-assets/load-assets-into-scenes.md
  scene-development/working-with-assets/optimize-assets-for-performance.md
  tutorials-and-examples/build-an-ecommerce-store/add-videos-to-your-store.md
  tutorials-and-examples/build-an-ecommerce-store/build-your-store-templates-and-ambiance.md
  tutorials-and-examples/build-an-ecommerce-store/configure-shopify-plugin.md
  tutorials-and-examples/build-an-ecommerce-store/load-and-place-shopify-products.md
  tutorials-and-examples/build-an-ecommerce-store/set-up-spatial-audio.md
Labels: documentation

#6 Complete navigation structure configuration and index page rework
  astro.config.mjs
  get-started/creating-projects/create-a-project.md
  get-started/creating-projects/understanding-entities.md
  get-started/initial-setup/sign-up-and-login.md
  get-started/initial-setup/system-requirements.md
  get-started/ir-engine-studio/introduction-to-the-studio.md
  get-started/ir-engine-studio/navigation-controls.md
  get-started/ir-engine-studio/studio-interface/file-browser-panel.md
  get-started/ir-engine-studio/studio-interface/hamburger-menu.md
  get-started/ir-engine-studio/studio-interface/hierarchy-tab.md
  get-started/ir-engine-studio/studio-interface/materials-inspector.md
  get-started/ir-engine-studio/studio-interface/properties-panel.md
  get-started/ir-engine-studio/studio-interface/viewport-panel.md
  introduction/about-this-site.md
  introduction/ir-engine-overview.md
  introduction/key-terminology.md
  publishing/publish-your-projects.md
  scene-development/building-and-managing-scenes/add-scenes-to-your-project.md
  scene-development/building-and-managing-scenes/scene-budget-guidelines.md
  scene-development/entities-and-components.md
  scene-development/working-with-assets/asset-types.md
  scene-development/working-with-assets/import-assets-and-files.md
  scene-development/working-with-assets/load-assets-into-scenes.md
  scene-development/working-with-assets/optimize-assets-for-performance.md
  src/content/docs/guides/get-started/creating-projects/create-a-project.md
  src/content/docs/guides/get-started/creating-projects/understanding-entities.md
  src/content/docs/guides/get-started/initial-setup/sign-up-and-login.md
  src/content/docs/guides/get-started/initial-setup/system-requirements.md
  src/content/docs/guides/get-started/ir-engine-studio/introduction-to-the-studio.md
  src/content/docs/guides/get-started/ir-engine-studio/navigation-controls.md
  src/content/docs/guides/get-started/ir-engine-studio/studio-interface/file-browser-panel.md
  src/content/docs/guides/get-started/ir-engine-studio/studio-interface/hamburger-menu.md
  src/content/docs/guides/get-started/ir-engine-studio/studio-interface/hierarchy-tab.md
  src/content/docs/guides/get-started/ir-engine-studio/studio-interface/materials-inspector.md
  src/content/docs/guides/get-started/ir-engine-studio/studio-interface/properties-panel.md
  src/content/docs/guides/get-started/ir-engine-studio/studio-interface/viewport-panel.md
  src/content/docs/guides/introduction/about-this-site.md
  src/content/docs/guides/introduction/ir-engine-overview.md
  src/content/docs/guides/introduction/key-terminology.md
  src/content/docs/guides/publishing/publish-your-projects.md
  src/content/docs/guides/scene-development/building-and-managing-scenes/add-scenes-to-your-project.md
  src/content/docs/guides/scene-development/building-and-managing-scenes/scene-budget-guidelines.md
  src/content/docs/guides/scene-development/entities-and-components.md
  src/content/docs/guides/scene-development/working-with-assets/asset-types.md
  src/content/docs/guides/scene-development/working-with-assets/import-assets-and-files.md
  src/content/docs/guides/scene-development/working-with-assets/load-assets-into-scenes.md
  src/content/docs/guides/scene-development/working-with-assets/optimize-assets-for-performance.md
  src/content/docs/guides/tutorials-and-examples/build-an-ecommerce-store/add-videos-to-your-store.md
  src/content/docs/guides/tutorials-and-examples/build-an-ecommerce-store/build-your-store-templates-and-ambiance.md
  src/content/docs/guides/tutorials-and-examples/build-an-ecommerce-store/configure-shopify-plugin.md
  src/content/docs/guides/tutorials-and-examples/build-an-ecommerce-store/load-and-place-shopify-products.md
  src/content/docs/guides/tutorials-and-examples/build-an-ecommerce-store/publish-your-store.md
  src/content/docs/guides/tutorials-and-examples/build-an-ecommerce-store/set-up-spatial-audio.md
  src/content/docs/index.mdx
  tutorials-and-examples/build-an-ecommerce-store/add-videos-to-your-store.md
  tutorials-and-examples/build-an-ecommerce-store/build-your-store-templates-and-ambiance.md
  tutorials-and-examples/build-an-ecommerce-store/configure-shopify-plugin.md
  tutorials-and-examples/build-an-ecommerce-store/load-and-place-shopify-products.md
  tutorials-and-examples/build-an-ecommerce-store/set-up-spatial-audio.md
Labels: enhancement

#7 Slug configuration for correct navigation after deployment
  astro.config.mjs
Labels: bug

#8 fix sub-page redirect
  iac/modules/static-website/append-index.js
  iac/modules/static-website/cloudfront.tf
Labels: verified-contributor
