Repository EtherealEngine/ir-engine-docs, pull requests merged in 2024-08, with the labels that each got.

#9 Introduction guides: Guides content + placeholders for images
  astro.config.mjs
  src/content/docs/guides/introduction/about-this-site.md
  src/content/docs/guides/introduction/glossary.md
  src/content/docs/guides/introduction/ir-engine-overview.md
  src/content/docs/guides/introduction/key-terminology.md
Labels: documentation

#10 Get started -> The iR Engine Studio: Guides content + placeholders for images
  astro.config.mjs
  src/content/docs/guides/get-started/ir-engine-studio/introduction-to-studio.md
  src/content/docs/guides/get-started/ir-engine-studio/introduction-to-the-studio.md
  src/content/docs/guides/get-started/ir-engine-studio/navigation-controls.md
  src/content/docs/guides/get-started/ir-engine-studio/studio-interface/file-browser-panel.md
  src/content/docs/guides/get-started/ir-engine-studio/studio-interface/hamburger-menu.md
  src/content/docs/guides/get-started/ir-engine-studio/studio-interface/hierarchy-tab.md
  src/content/docs/guides/get-started/ir-engine-studio/studio-interface/materials-inspector.md
  src/content/docs/guides/get-started/ir-engine-studio/studio-interface/properties-panel.md
  src/content/docs/guides/get-started/ir-engine-studio/studio-interface/viewport-panel.md
Labels: documentation

#11 Get started -> Initial setup: Guides content + placeholders for images
  astro.config.mjs
  src/content/docs/guides/get-started/creating-projects/create-a-project.md
  src/content/docs/guides/get-started/creating-projects/understanding-entities.md
  src/content/docs/guides/get-started/initial-setup/sign-up-and-login.md
  src/content/docs/guides/get-started/initial-setup/start-a-new-project.md
Labels: documentation

#12 Scene development -> Build and manage scenes: Guide content (Add scenes to your project) + placeholders for images
  astro.config.mjs
  src/content/docs/guides/scene-development/building-and-managing-scenes/add-scenes-to-your-project.md
  src/content/docs/guides/scene-development/building-and-managing-scenes/scene-budget-guidelines.md
  src/content/docs/guides/scene-development/entities-and-components.md
Labels: documentation

#13 Scene development -> Work with assets: Guides content + placeholders for images
  astro.config.mjs
  src/content/docs/guides/scene-development/working-with-assets/asset-types-guide.md
  src/content/docs/guides/scene-development/working-with-assets/asset-types.md
  src/content/docs/guides/scene-development/working-with-assets/import-assets-and-files.md
  src/content/docs/guides/scene-development/working-with-assets/import-files-and-assets.md
  src/content/docs/guides/scene-development/working-with-assets/load-assets-into-scenes.md
  src/content/docs/guides/scene-development/working-with-assets/optimize-assets-for-performance.md
Labels: documentation

#14 Publish your projects: Guide content + placeholders for images + nav improvements
  astro.config.mjs
  src/content/docs/guides/get-started/initial-setup/system-requirements.md
  src/content/docs/guides/get-started/ir-engine-studio/studio-interface/viewport-panel.md
  src/content/docs/guides/introduction/ir-engine-overview.md
  src/content/docs/guides/publishing/publish-your-projects.md
  src/content/docs/guides/scene-development/building-and-managing-scenes/scene-budget-guidelines.md
Labels: documentation

#15 Tutorials -> Build an ecommerce store: Guide content + placeholders for images
  astro.config.mjs
  src/content/docs/guides/publishing/publish-your-projects.md
  src/content/docs/guides/tutorials-and-examples/build-an-ecommerce-store/add-videos-to-your-store.md
  src/content/docs/guides/tutorials-and-examples/build-an-ecommerce-store/build-your-store-templates-and-ambiance.md
  src/content/docs/guides/tutorials-and-examples/build-an-ecommerce-store/configure-shopify-plugin.md
  src/content/docs/guides/tutorials-and-examples/build-an-ecommerce-store/introduction-and-prerequisites.md
  src/content/docs/guides/tutorials-and-examples/build-an-ecommerce-store/load-and-place-shopify-products.md
  src/content/docs/guides/tutorials-and-examples/build-an-ecommerce-store/publish-your-store.md
  src/content/docs/guides/tutorials-and-examples/build-an-ecommerce-store/set-up-spatial-audio.md
Labels: documentation

#16 Quick typo fix
  src/content/docs/guides/introduction/ir-engine-overview.md
Labels: bug

#20 Fix: Incorrect image referencing causing the build to fail
  src/assets/images/tutorials-and-examples/build-an-ecommerce-store-with-shopify-integration/publish-your-store/create-location-modal.png
  src/assets/images/tutorials-and-examples/build-an-ecommerce-store-with-shopify-integration/publish-your-store/publish-button-location.png
Labels: bug

#21 New: Hyperlinks and crossferences
  src/content/docs/get-started/initial-setup/sign-up-and-login.md
  src/content/docs/get-started/initial-setup/start-a-new-project.md
  src/content/docs/get-started/ir-engine-studio/introduction-to-studio.md
  src/content/docs/get-started/ir-engine-studio/navigation-controls.md
  src/content/docs/get-started/ir-engine-studio/studio-interface/viewport-panel.md
  src/content/docs/introduction/about-this-site.md
  src/content/docs/scene-development/working-with-assets/import-files-and-assets.md
  src/content/docs/scene-development/working-with-assets/load-assets-into-scenes.md
  src/content/docs/tutorials-and-examples/build-an-ecommerce-store/add-videos-to-your-store.md
  src/content/docs/tutorials-and-examples/build-an-ecommerce-store/build-your-store-templates-and-ambiance.md
  src/content/docs/tutorials-and-examples/build-an-ecommerce-store/configure-shopify-plugin.md
  src/content/docs/tutorials-and-examples/build-an-ecommerce-store/introduction-and-prerequisites.md
  src/content/docs/tutorials-and-examples/build-an-ecommerce-store/load-and-place-shopify-products.md
  src/content/docs/tutorials-and-examples/build-an-ecommerce-store/set-up-spatial-audio.md
Labels: documentation

#22 remove ignoring md files
  .github/workflows/deploy-docs-site.yml
Labels: verified-contributor

#23 New: Inline icons and images for guides.
  src/content/docs/get-started/ir-engine-studio/studio-interface/file-browser-panel.md
  src/content/docs/get-started/ir-engine-studio/studio-interface/viewport-panel.md
Labels: documentation, enhancement

#24 Fix: Path reference for icons in HTML tags.
  src/content/docs/get-started/ir-engine-studio/studio-interface/file-browser-panel.md
  src/content/docs/get-started/ir-engine-studio/studio-interface/viewport-panel.md
Labels: bug

#25 Fix: Icon referencing by using relative paths
  src/content/docs/get-started/ir-engine-studio/studio-interface/file-browser-panel.md
  src/content/docs/get-started/ir-engine-studio/studio-interface/viewport-panel.md
Labels: bug

#26 Fix: Icon images referenced with HTML tags not showing. Moved to public dir to fix this issue.
  public/assets/images/file-browser-icons/create-folder-button.png
  public/assets/images/file-browser-icons/download-project-button.png
  public/assets/images/file-browser-icons/file-location-bar.png
  public/assets/images/file-browser-icons/list-view-button.png
  public/assets/images/file-browser-icons/refresh-button.png
  public/assets/images/file-browser-icons/search-bar.png
  public/assets/images/file-browser-icons/thumbnails-view-button.png
  public/assets/images/file-browser-icons/view-options-button.png
  public/assets/images/viewport-panel-icons/lit-mode-icon.png
  public/assets/images/viewport-panel-icons/normals-mode-icon.png
  public/assets/images/viewport-panel-icons/shadows-mode-icon.png
  public/assets/images/viewport-panel-icons/unlit-mode-icon.png
  public/assets/images/viewport-panel-icons/wireframe-mode-icon.png
  src/content/docs/get-started/ir-engine-studio/studio-interface/file-browser-panel.md
  src/content/docs/get-started/ir-engine-studio/studio-interface/viewport-panel.md
Labels: bug

#27 New: Branding - adding logo and home icon to home page
  astro.config.mjs
  src/assets/irlogo_studio_purple_iso.png
  src/assets/site-logo-white.png
  src/content/docs/index.mdx
Labels: enhancement

#28 Nav changes and image fix
  astro.config.mjs
  src/assets/images/scene-development/build-and-manage-scenes/add-scenes-to-your-project/add-scene-button-location.png
  src/content/docs/get-started/ir-engine-studio/introduction-to-studio.md
  src/content/docs/index.mdx
Labels: enhancement

#29 New: Scene resource management document
  astro.config.mjs
  src/content/docs/get-started/initial-setup/system-requirements.md
  src/content/docs/scene-development/building-and-managing-scenes/scene-budget-guidelines.md
  src/content/docs/scene-development/building-and-managing-scenes/scene-resource-guidelines.md
Labels: documentation

#31 New: Rich link preview when sharing the docs site URL
  astro.config.mjs
  public/assets/link-preview-background.png
  src/content/docs/index.mdx
Labels: enhancement

#32 Fix: Link preview image configuration when sharing the URL of the docs site
  astro.config.mjs
Labels: bug

#33 New: Open Graph tags to ensure correct link preview rendering in multiple platforms
  astro.config.mjs
Labels: enhancement

#34 New: iR Engine favicon added to the docs site
  astro.config.mjs
  public/favicon-32x32.png
Labels: enhancement

#35 New: Enhance visual presentation of images in Markdown documents
  src/styles/custom.css
Labels: enhancement

#36 New: Embedding your world using iFrame guide
  astro.config.mjs
  src/content/docs/publishing/embed-worlds-into-websites.md
Labels: documentation

#37 New: Share modal screen for embedding iFrame and wording improvements
  src/assets/images/publishing/publish-your-projects/share-menu-embed-option.png
  src/content/docs/publishing/embed-worlds-into-websites.md
Labels: documentation

#38 New: Site navigation with card structure to enhance user experience.
  astro.config.mjs
  src/content/docs/index.mdx
  src/content/docs/site-navigation.mdx
Labels: enhancement

#39 New: Steps visual UX improvement for guided instructions | 'Steps' component
  public/assets/images/viewport-panel-icons/lit-mode-icon.png
  public/assets/images/viewport-panel-icons/unlit-mode-icon.png
  src/content/docs/get-started/initial-setup/sign-up-and-login.mdx
  src/content/docs/get-started/initial-setup/start-a-new-project.mdx
  src/content/docs/get-started/ir-engine-studio/studio-interface/materials-inspector.mdx
  src/content/docs/publishing/embed-worlds-into-websites.mdx
  src/content/docs/publishing/publish-your-projects.mdx
  src/content/docs/scene-development/building-and-managing-scenes/add-scenes-to-your-project.mdx
  src/content/docs/scene-development/working-with-assets/import-files-and-assets.mdx
  src/content/docs/scene-development/working-with-assets/load-assets-into-scenes.mdx
  src/content/docs/scene-development/working-with-assets/optimize-assets-for-performance.md
  src/content/docs/tutorials-and-examples/build-an-ecommerce-store/add-videos-to-your-store.mdx
  src/content/docs/tutorials-and-examples/build-an-ecommerce-store/build-your-store-templates-and-ambiance.mdx
  src/content/docs/tutorials-and-examples/build-an-ecommerce-store/configure-shopify-plugin.mdx
  src/content/docs/tutorials-and-examples/build-an-ecommerce-store/introduction-and-prerequisites.mdx
  src/content/docs/tutorials-and-examples/build-an-ecommerce-store/load-and-place-shopify-products.mdx
  src/content/docs/tutorials-and-examples/build-an-ecommerce-store/publish-your-store.mdx
  src/content/docs/tutorials-and-examples/build-an-ecommerce-store/set-up-spatial-audio.mdx
Labels: enhancement

#40 New: Light mode configurations
  astro.config.mjs
  src/assets/houston.webp
  src/assets/site-logo-black.png
  src/styles/custom.css
Labels: enhancement

#41 Opens the engine on a different tab.
  src/content/docs/index.mdx
Labels: documentation

#42 Fix iFrame formatting correction
  src/content/docs/publishing/embed-worlds-into-websites.mdx
Labels: bug

#43 New: Adds images to the embed 3d world guide
  src/assets/images/publishing/embed-worlds-into-websites/3d-world-location.png
  src/assets/images/publishing/embed-worlds-into-websites/share-button.png
  src/assets/images/publishing/embed-worlds-into-websites/share-menu-embed-option.png
  src/content/docs/publishing/embed-worlds-into-websites.mdx
Labels: documentation

#44 New: Release notes page placeholder and template
  astro.config.mjs
  src/content/docs/release-notes.mdx
Labels: documentation

#45 New: First version of Release notes for v1.0
  src/content/docs/release-notes.mdx
Labels: documentation

#46 Changes v1.0 to v0.8. As per Chris Ball's request.
  src/content/docs/release-notes.mdx
Labels: documentation

#47 Changed format to MDX to correctly render Steps components.
  src/content/docs/scene-development/working-with-assets/optimize-assets-for-performance.mdx
Labels: bug

#48 New: Shortcuts and hotkeys guide.
  astro.config.mjs
  src/content/docs/get-started/ir-engine-studio/shortcuts-and-hotkeys.md
Labels: documentation
